# Generated by Django 3.2.13 on 2022-04-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='race',
            field=models.CharField(default='white', max_length=10),
            preserve_default=False,
        ),
    ]
