# Generated by Django 3.2.13 on 2022-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220419_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='race',
            field=models.CharField(max_length=1000),
        ),
    ]
